Imported Upstream version 2.6.10

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,17 +1,24 @@
 
-SUBDIRS = . doc lib src intl-scm packaging po accounts checks
-
-docdir = ${GNC_DOC_INSTALL_DIR}
+SUBDIRS = . doc lib src packaging po accounts checks
 
 GNC_CTAGS_FILE = @GNC_CTAGS_FILE@
 GNC_ETAGS_FILE = @GNC_ETAGS_FILE@
 
 noinst_DATA = make-gnucash-potfiles
 
+noinst_PROGRAMS    = gnc-guile
+gnc_guile_SOURCES = util/guile.c
+gnc_guile_CFLAGS  = ${GUILE_CFLAGS}
+gnc_guile_LDADD   = ${GUILE_LIBS}
+
 dist_doc_DATA = \
   AUTHORS \
   COPYING \
   ChangeLog \
+  ChangeLog.2014 \
+  ChangeLog.2013 \
+  ChangeLog.2012 \
+  ChangeLog.2011 \
   ChangeLog.2010 \
   ChangeLog.2009 \
   ChangeLog.2008 \
@@ -40,12 +47,14 @@ dist_doc_DATA = \
 # CVS dirs.
 
 EXTRA_DIST = \
+  $(SWIG_DIST_FAIL) \
   make-gnucash-potfiles.in \
   macros/as-scrub-include.m4 \
   macros/binreloc.m4 \
   macros/compiler-flags.m4 \
-  macros/ac_pkg_swig.m4 \
-  macros/gnome-guile-checks.m4 \
+  macros/ax_pkg_swig.m4 \
+  macros/ax_python_devel.m4 \
+  macros/ax_swig_python.m4 \
   macros/legacy_macros.m4 \
   po/gnucash.pot \
   po/POTFILES.in \
@@ -80,7 +89,7 @@ EXTRA_DIST = \
   intltool-extract.in \
   intltool-merge.in \
   intltool-update.in \
-  util/gnc-svnversion
+  util/gnc-vcs-info
 
 ## We borrow guile's convention and use @-...-@ as the substitution
 ## brackets here, instead of the usual @...@.  This prevents autoconf
@@ -145,15 +154,23 @@ distuninstallcheck_listfiles = \
 
 #dist-hook: po/POTFILES.in
 
+# Make "make dist" fail if we have the wrong version of swig
+if SWIG_DIST_FAIL
+SWIG_DIST_FAIL = swig-dist-fail
+swig-dist-fail:
+	@echo "You cannot build the dist with your version of swig"
+	@exit 1
+endif
+
 distcheck-hook:
 	@e=''; \
-	for X in `grep -v \# ${distdir}/po/POTFILES.in` ; do \
+	for X in `grep -v \# ${distdir}/po/POTFILES.in | sed 's/\[type:.*\]//'` ; do \
 		if [ ! -f ${distdir}/$$X ] ; then \
 			echo $$X " is in POTFILES.in but not in the dist."; \
 			e='yes'; \
 		fi; \
 	done; \
-	for X in `grep -v \# ${distdir}/po/POTFILES.skip` ; do \
+	for X in `grep -v '\(^\#\|.scm\$\)' ${distdir}/po/POTFILES.skip` ; do \
 		if [ -f ${distdir}/$$X ] ; then \
 			echo $$X " is in POTFILES.skip but also in the dist.";\
 			e='yes'; \
@@ -168,8 +185,6 @@ libtool: $(LIBTOOL_DEPS)
 
 .PHONY: pot
 pot: Makefile po/POTFILES.in
-	rm -f intl-scm/guile-strings.c
-	${MAKE} -C intl-scm
 	rm -f po/$(PACKAGE).pot
 	${MAKE} -C po $(PACKAGE).pot
 
@@ -179,26 +194,34 @@ $(srcdir)/po/POTFILES.in: make-gnucash-potfiles .potfiles
 
 # Creation rules so that po/gnucash.pot can always be created for
 # make dist.
-po/gnucash.pot: po/POTFILES.in intl-scm/guile-strings.c
+po/gnucash.pot: po/POTFILES.in
 	${MAKE} -C po gnucash.pot
-intl-scm/guile-strings.c:
-	${MAKE} -C intl-scm guile-strings.c
 
 .potfiles:
 
 SVN = svn
-XSLTPROC = xsltproc
 
-if BUILDING_FROM_SVN
+if BUILDING_FROM_VCS
 # This rule will generate a ChangeLog of gnucash/trunk commits, plus
 # all additional branches that are added in
 # ./macros/svn2cl.xsl. (FIXME: Is the dependency on NEWS really a good
 # idea? Before a release, NEWS will get updated because of the version
 # change, so this should fit just fine.)
 ChangeLog: NEWS
-	$(SVN) log -v --xml -r HEAD:20021 http://svn.gnucash.org/repo/gnucash | \
-	  $(XSLTPROC) --stringparam strip-prefix "gnucash/trunk" \
-	  --stringparam include-rev "yes" $(srcdir)/macros/svn2cl.xsl - > $@
+	cd $(abs_srcdir) ; \
+	if test x$(VCS_TYPE) = xsvn ; then \
+	  $(SVN) log -v --xml -r HEAD:'{2015-01-01}' http://svn.gnucash.org/repo/gnucash | \
+	    $(XSLTPROC) --stringparam strip-prefix "gnucash/trunk" \
+	    --stringparam include-rev "yes" $(abs_srcdir)/macros/svn2cl.xsl - > $(abs_builddir)/$@ ; \
+	else \
+	  if test x$(VCS_TYPE) = xgit ; then \
+	    "$(GIT_CMD)" log --format="%ad %aN %n%n%x09* %s%d%n" --date=short --since=2013-01-01 > $(abs_builddir)/$@ ; \
+	  else \
+	    touch $(abs_builddir)/$@ ; \
+	    echo "Note: not in svn or git. ChangeLog not regenerated." ; \
+	  fi ; \
+	fi ; \
+	cd $(abs_builddir)
 endif
 
 ASTYLE = /usr/bin/astyle
@@ -210,3 +233,4 @@ indent:
 # a very ugly way.
 #	$(ASTYLE) --indent=spaces=4 --brackets=break --pad-oper -pad-header --suffix=none `find ${srcdir}/src -name '*.[hc]'`
 	@echo "### GnuCash development hint: The above command might have re-indented much more files than what you intended. Please commit only those which you really want to have changed, and revert the changes in the others so that other devevelopers do not have unnecessary merge conflicts. Thanks! ###"
+
