New upstream version 3.0

diff --git a/util/gnc-vcs-info b/util/gnc-vcs-info
--- a/util/gnc-vcs-info
+++ b/util/gnc-vcs-info
@@ -2,9 +2,11 @@
 #
 # Usage:
 #   gnc-vcs-info -r <srcdir>
+#   gnc-vcs-info -d <srcdir>
 #   gnc-vcs-info -t <srcdir>
 #
 # With -r prints the revision number to stdout and exits 0 on success
+# With -d prints the commit date to stdout and exits 0 on success
 # With -t prints the vcs type that was detected to stdout and exits 0
 #         on success.
 #
@@ -17,6 +19,7 @@
 
 # Default string to return if not invoked properly
 usage="Usage: $0 -r <srcdir>
+       $0 -d <srcdir>
        $0 -t <srcdir>"
 
 # Print an error message and then exit
@@ -49,6 +52,9 @@ then
 elif [ "$1" = "-r" ]
 then
   request="revision"
+elif [ "$1" = "-d" ]
+then
+  request="date"
 else
   my_die "$usage"
 fi
@@ -58,9 +64,9 @@ srcdir=$2
 # Find the real srcdir.
 # This handles the case of a symlink (lndir) tree
 # $real_srcdir will hold the actual source dir
-if test -h "$srcdir"/Makefile.am
+if test -h "$srcdir"/CMakeLists.txt
 then 
-  tmp_srcdir=`readlink "$srcdir"/Makefile.am`
+  tmp_srcdir=`readlink "$srcdir"/CMakeLists.txt`
   real_srcdir="$srcdir/`dirname ${tmp_srcdir}`"
 else
   real_srcdir="$srcdir"
@@ -74,6 +80,12 @@ then
   if [ "$request" = "type" ]
   then
     echo "svn"
+    exit 0
+  fi
+
+  if [ "$request" = "date" ]
+  then
+    echo $(svn info "$real_srcdir}" | awk '/Last Changed Date/ { print $4 }')
     exit 0
   fi
 
@@ -92,10 +104,9 @@ then
 fi
 
 # If we get here then this is NOT an svn checkout.
-
 # Maybe it's git?
 real_gitdir="${real_srcdir}"/.git
-if test -d "${real_gitdir}"
+if test -d "${real_gitdir}" || test -e "${real_gitdir}"
 then
   # If we're only interested in the vcs type, then we're done here
   if [ "$request" = "type" ]
@@ -108,8 +119,21 @@ then
   # to the PATH in Windows results in a build failure).
   # So for platform independence, use GIT_CMD for all
   [ -n "$GIT_CMD" ] || GIT_CMD=git
-  githead=`"$GIT_CMD" --git-dir "${real_gitdir}" log -1 --pretty=format:"%h" HEAD 2>/dev/null`  # short hash only
-  if test $? = 0 ; then
+  if [ "$request" = "date" ]
+  then
+    exec "$GIT_CMD" --git-dir "${real_gitdir}" log -1 --format=%cd --date=short
+    exit 0
+  fi
+
+  githead=$("$GIT_CMD" --git-dir "${real_gitdir}" describe 2>/dev/null)
+  rc=$?
+  if [ $rc != 0 ]; then
+    # On travis describe seems to fail due to missing tags in the git clone the system takes
+    # So specifically to catch those errors, use only the short commit hash as a backup
+    githead=$("$GIT_CMD" --git-dir "${real_gitdir}" log -1 --pretty=format:"%h" HEAD 2>/dev/null)
+    rc=$?
+  fi
+  if [ $rc = 0 ]; then
     /bin/echo -n $githead
     # Add a "+" to the hash if there deleted or modified files (not excluded by .gitignore and friends)
     # "Ignores" untracked files
@@ -129,6 +153,13 @@ then
   if [ "$request" = "type" ]
   then
     echo "bzr"
+    exit 0
+  fi
+
+  if [ "$request" = "date" ]
+  then
+    # FIXME Don't know how to extract the commit's date from a bzr commit...
+    echo $(date +%Y-%m-%d)
     exit 0
   fi
 
@@ -168,6 +199,14 @@ then
   echo "svk"
   exit 0
 fi
+
+if [ "$request" = "date" ]
+then
+  # FIXME Don't know how to extract the commit's date from an svk commit...
+  echo $(date +%Y-%m-%d)
+  exit 0
+fi
+
 
 # Parse out the revision info, print it out, and then output 0.  Just combine
 # all the revision numbers into a single string by combining them
